"""AgentSession/Turn 专用持久化端口。"""

from typing import Protocol

from literature_agent.domain.research_agent import (
    AgentArtifactCandidate,
    AgentMessage,
    AgentSession,
    AgentTurnRun,
    ContextSnapshot,
    PolicySnapshot,
    RuntimeSessionBinding,
    RuntimeTurnBinding,
)


class AgentRepository(Protocol):
    """保存 Agent 业务事实；不暴露 Runtime SDK 类型。"""

    async def add_session(self, value: AgentSession) -> AgentSession: ...
    async def list_sessions_scoped(
        self, project_id: str, owner_id: str
    ) -> list[AgentSession]: ...
    async def get_session_scoped(self, session_id: str, owner_id: str) -> AgentSession | None: ...
    async def get_session_scoped_for_update(
        self, session_id: str, owner_id: str
    ) -> AgentSession | None: ...
    async def try_claim_active_turn(self, session_id: str, turn_run_id: str) -> bool: ...
    async def release_active_turn(self, session_id: str, turn_run_id: str) -> bool: ...
    async def allocate_message_sequence(self, session_id: str) -> int: ...
    async def add_message(self, value: AgentMessage) -> AgentMessage: ...
    async def list_messages_scoped(self, session_id: str, owner_id: str) -> list[AgentMessage]: ...
    async def has_messages(self, session_id: str) -> bool: ...
    async def get_message_by_run_and_role(self, run_id: str, role: str) -> AgentMessage | None: ...
    async def add_turn(self, value: AgentTurnRun) -> AgentTurnRun: ...
    async def get_turn_scoped(self, run_id: str, owner_id: str) -> AgentTurnRun | None: ...
    async def add_context_snapshot(self, value: ContextSnapshot) -> ContextSnapshot: ...
    async def get_context_snapshot(self, snapshot_id: str) -> ContextSnapshot | None: ...
    async def add_policy_snapshot(self, value: PolicySnapshot) -> PolicySnapshot: ...
    async def get_policy_snapshot(self, snapshot_id: str) -> PolicySnapshot | None: ...
    async def get_or_add_session_binding(
        self, value: RuntimeSessionBinding
    ) -> RuntimeSessionBinding: ...
    async def get_or_add_turn_binding(self, value: RuntimeTurnBinding) -> RuntimeTurnBinding: ...
    async def get_session_binding(self, session_id: str) -> RuntimeSessionBinding | None: ...
    async def get_session_binding_generation(
        self, session_id: str, generation: int
    ) -> RuntimeSessionBinding | None: ...
    async def get_turn_binding(self, run_id: str) -> RuntimeTurnBinding | None: ...
    async def get_or_add_candidate(
        self, value: AgentArtifactCandidate
    ) -> AgentArtifactCandidate: ...
    async def list_candidates_scoped(
        self, run_id: str, owner_id: str
    ) -> list[AgentArtifactCandidate]: ...
