"""Agent Turn Usage 与 Tool 调用摘要持久化端口。"""

from typing import Protocol

from literature_agent.domain.agent_usage import (
    AgentModelCallReservation,
    AgentToolCall,
    AgentToolCallStatus,
    AgentTurnUsage,
)


class AgentUsageRepository(Protocol):
    async def add_usage(self, value: AgentTurnUsage) -> AgentTurnUsage: ...
    async def get_usage(self, turn_run_id: str) -> AgentTurnUsage | None: ...
    async def get_usage_for_update(self, turn_run_id: str) -> AgentTurnUsage | None: ...
    async def save_usage(self, value: AgentTurnUsage) -> None: ...
    async def get_model_call(self, reservation_key: str) -> AgentModelCallReservation | None: ...
    async def add_model_call(
        self, value: AgentModelCallReservation
    ) -> AgentModelCallReservation: ...
    async def save_model_call(self, value: AgentModelCallReservation) -> None: ...
    async def get_tool_call(self, reservation_key: str) -> AgentToolCall | None: ...
    async def add_tool_call(self, value: AgentToolCall) -> AgentToolCall: ...
    async def list_tool_calls(self, turn_run_id: str) -> list[AgentToolCall]: ...
    async def count_tool_calls_by_signature(
        self, turn_run_id: str, tool_name: str, args_hash: str
    ) -> int: ...
    async def save_tool_call(
        self,
        value: AgentToolCall,
        *,
        expected_status: AgentToolCallStatus,
    ) -> bool: ...
