"""Owner Skill 不可变版本与 Session Profile 持久化端口。"""

from typing import Protocol

from literature_agent.domain.skill_configuration import (
    OwnerSkill,
    SkillProfile,
    SkillVersion,
)


class SkillRepository(Protocol):
    async def list_owner_skills(self, owner_id: str) -> list[SkillVersion]: ...
    async def get_owner_skill(
        self, skill_id: str, owner_id: str, *, for_update: bool = False
    ) -> OwnerSkill | None: ...
    async def get_owner_skill_by_name(self, owner_id: str, name: str) -> OwnerSkill | None: ...
    async def get_owner_version(
        self, skill_id: str, version: int, owner_id: str
    ) -> SkillVersion | None: ...
    async def get_latest_owner_version(
        self, skill_id: str, owner_id: str, *, for_update: bool = False
    ) -> SkillVersion | None: ...
    async def add_owner_skill(self, value: OwnerSkill) -> bool: ...
    async def add_version(self, value: SkillVersion) -> SkillVersion: ...
    async def get_profile(self, session_id: str, owner_id: str) -> SkillProfile | None: ...
    async def get_profile_for_update(
        self, session_id: str, owner_id: str
    ) -> SkillProfile | None: ...
    async def add_profile(self, value: SkillProfile) -> SkillProfile: ...
    async def save_profile(self, value: SkillProfile, *, expected_revision: int) -> bool: ...
