"""create run_attempts table

Revision ID: 28a3aeb62280
Revises: 13497f1b8554
Create Date: 2026-08-20 02:53:48.888362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a3aeb62280'
down_revision: Union[str, Sequence[str], None] = '13497f1b8554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('run_id', 'attempt_number', name='uq_run_attempts_run_attempt')
    )
    op.create_index(op.f('ix_run_attempts_heartbeat_at'), 'run_attempts', ['heartbeat_at'], unique=False)
    op.create_index(op.f('ix_run_attempts_run_id'), 'run_attempts', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_attempts_status'), 'run_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_attempts_status'), table_name='run_attempts')
    op.drop_index(op.f('ix_run_attempts_run_id'), table_name='run_attempts')
    op.drop_index(op.f('ix_run_attempts_heartbeat_at'), table_name='run_attempts')
    op.drop_table('run_attempts')
    # ### end Alembic commands ###
