"""create papers paper versions and idempotency keys

Revision ID: 3ce12fa8e5a5
Revises: 2e593406e3e6
Create Date: 2026-08-19 18:14:47.613943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce12fa8e5a5'
down_revision: Union[str, Sequence[str], None] = '2e593406e3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_index(op.f('ix_papers_owner_id'), 'papers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_papers_project_id'), 'papers', ['project_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'idempotency_key')
    )
    op.create_table('paper_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_paper_versions_paper_id'), 'paper_versions', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_versions_paper_id'), table_name='paper_versions')
    op.drop_table('paper_versions')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_papers_project_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_owner_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
