"""create parse revision and element tables

Revision ID: 8865966463a6
Revises: a4e0bc996e3b
Create Date: 2026-08-19 21:52:01.091797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8865966463a6'
down_revision: Union[str, Sequence[str], None] = 'a4e0bc996e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_parse_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('parser_name', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('parser_profile_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['paper_versions.version_id'], ),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('version_id', 'parser_profile_hash', name='uq_parse_revisions_version_profile')
    )
    op.create_index(op.f('ix_document_parse_revisions_version_id'), 'document_parse_revisions', ['version_id'], unique=False)
    op.create_table('document_elements',
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('element_type', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('parent_element_id', sa.String(length=36), nullable=True),
    sa.Column('section_path', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_element_id'], ['document_elements.element_id'], use_alter=True),
    sa.ForeignKeyConstraint(['revision_id'], ['document_parse_revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('element_id'),
    sa.UniqueConstraint('revision_id', 'sequence', name='uq_elements_revision_sequence')
    )
    op.create_index(op.f('ix_document_elements_revision_id'), 'document_elements', ['revision_id'], unique=False)
    op.create_table('element_source_locations',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_ref', sa.String(length=255), nullable=True),
    sa.Column('char_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['document_elements.element_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_element_source_locations_element_id'), 'element_source_locations', ['element_id'], unique=False)
    op.add_column('paper_versions', sa.Column('current_parse_revision_id', sa.String(length=36), nullable=True))
    # 显式约束名沿用 PostgreSQL 单列外键自动命名规则（{table}_{column}_fkey），
    # 与存量数据库中已生成的约束名一致，保证 upgrade 行为不变、downgrade 可按名 DROP。
    op.create_foreign_key(
        'paper_versions_current_parse_revision_id_fkey',
        'paper_versions',
        'document_parse_revisions',
        ['current_parse_revision_id'],
        ['revision_id'],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'paper_versions_current_parse_revision_id_fkey',
        'paper_versions',
        type_='foreignkey',
    )
    op.drop_column('paper_versions', 'current_parse_revision_id')
    op.drop_index(op.f('ix_element_source_locations_element_id'), table_name='element_source_locations')
    op.drop_table('element_source_locations')
    op.drop_index(op.f('ix_document_elements_revision_id'), table_name='document_elements')
    op.drop_table('document_elements')
    op.drop_index(op.f('ix_document_parse_revisions_version_id'), table_name='document_parse_revisions')
    op.drop_table('document_parse_revisions')
    # ### end Alembic commands ###
