"""create queue outbox table

Revision ID: a4e0bc996e3b
Revises: 3ce12fa8e5a5
Create Date: 2026-08-19 20:33:48.891128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e0bc996e3b'
down_revision: Union[str, Sequence[str], None] = '3ce12fa8e5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_outbox',
    sa.Column('outbox_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_queue_outbox_scheduled_at'), 'queue_outbox', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_queue_outbox_status'), 'queue_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_outbox_status'), table_name='queue_outbox')
    op.drop_index(op.f('ix_queue_outbox_scheduled_at'), table_name='queue_outbox')
    op.drop_table('queue_outbox')
    # ### end Alembic commands ###
